version: '3'

services:
  # React App
  front-end:
    restart: always
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run front-end:dev:docker
    ports:
      - 4201:4200

  # back-end
  back-end:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run back-end:dev:docker
    ports:
      - 3333:3333 # API Entry port
      - 4311:4311 # Server Debugging port

  # db
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: findhotel
    ports:
      - "3307:3306"

volumes:
  mono-node-modules: null
  todo-mysql-data:

