version: '3'

services:
  # React App
  front-end:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run front-end:dev:docker
    ports:
      - 4201:4200

  # back-end
  back-end:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run back-end:dev:docker
    ports:
      - 4310:3333 # API Entry port
      - 4311:4311 # Server Debugging port

volumes:
  mono-node-modules: null