apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: betty713/back-end
      context: .
      docker:
        dockerfile: apps/back-end/Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: betty713/front-end
      context: .
      docker:
        dockerfile: apps/front-end/Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
