FROM docker.io/node:lts-alpine

WORKDIR /app

RUN addgroup --system back-end && \
          adduser --system -G back-end back-end

COPY . .

RUN chown -R back-end:back-end .
RUN npm install --omit=dev

CMD [ "npx", "nx", "run", "back-end:serve" ]