POST http://localhost:3333/api/rooms
content-type: application/json

{
  "name": "豪華雙人房",
  "type": 2,
  "defaultPrice": 4000,
  "discountPrice": 2400,
  "facilities": [0,1,2],
  "people": 2,
  "pictures": [
    "https://image-store.asiayo.com/bnb/38649/960xauto/desc_8MU7ew70K6OCFm.jpg",
    "https://image-store.asiayo.com/bnb/25993/960xauto/desc_5WyvN3f4rVbMiz.jpg",
    "https://image-store.asiayo.com/bnb/38649/370xauto/desc_aiSWIiLX3cBIPj.jpg"
  ],
  "hotelId": 9,
  "amount": 3
}
