apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - name: back-end
          image: betty713/back-end
          env: 
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: CLIETN_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://back-end-mongo-srv:27017/back-end'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: back-end-srv
spec: 
  selector:
    app: back-end
  ports:
    - name: back-end
      protocol: TCP
      port: 3333
      targetPort: 3333
