apiVersion: apps/v1
kind: Deployment
metadata:
  name: findhotel-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: findhotel
  template:
    metadata:
      labels:
        app: findhotel
    spec:
      containers:
        - name: findhotel
          image: betty713/findhotel
          env:
            - name: NX_BASE_URL_SERVER
              value: 'http://findhotel-srv:3333/api'
            - name: NX_BASE_URL_CLIENT
              value: ''
            - name: COOKIE_KEY
              value: 'alskdfjlkj'
            - name: DB_NAME
              value: 'mysql'
            - name: DB_HOST
              value: 'find-hotel-db-do-user-16085651-0.c.db.ondigitalocean.com'
            - name: DB_PORT
              value: '25060'
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: db-user-secret
                  key: DB_USER_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              value: 'defaultdb'

---
apiVersion: v1
kind: Service
metadata:
  name: findhotel-srv
spec:
  selector:
    app: findhotel
  ports:
    - name: front-end
      protocol: TCP
      port: 4200
      targetPort: 4200
    - name: back-end
      protocol: TCP
      port: 3333
      targetPort: 3333
