apiVersion: apps/v1
kind: Deployment
metadata:
  name: findhotel-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: findhotel
  template:
    metadata:
      labels:
        app: findhotel
    spec:
      containers:
        - name: findhotel
          image: betty713/findhotel
---
apiVersion: v1
kind: Service
metadata:
  name: findhotel-srv
spec:
  selector:
    app: findhotel
  ports:
    - name: front-end
      protocol: TCP
      port: 4200
      targetPort: 4200
    - name: back-end
      protocol: TCP
      port: 3333
      targetPort: 3333
