POST http://localhost:3333/api/hotels
content-type: application/json

{
  "phone": "0988888990",
  "name": "王子大飯店",
  "address": "台中南屯区向上路三段221號",
  "pictures": [
    "https://image-store.asiayo.com/bnb/37530/960xauto/desc_ALXAn5QnawpTvI.jpg",
    "https://image-store.asiayo.com/bnb/37530/960xauto/desc_vUQCARuPUMpEPP.jpg",
    "https://image-store.asiayo.com/bnb/37530/960xauto/desc_QQeviRMlU6Y8Vr.jpg"
  ],
  "checkInTime": "14:00",
  "checkOutTime": "11:00",
  "facilities": [1,3,4]
}

### find rooms by hotel
GET http://localhost:3333/api/hotels/findRooms?hotelId=8

### find available hotle
GET http://localhost:3333/api/hotels?startDate=2023-03-01T14:57:21.141Z&endDate=2023-03-02T14:57:21.141Z&adult=2&room=1

### find hotel details
GET http://localhost:3333/api/hotels/8
